### ISSUE TITLE
where to download pytorch_model.bin

### ISSUE THREAD

**Issue by cliff0412** [chenyangh/SemEval2019Task3#3]
when i run the trainer_hrlce.py, the model is built using lstm. 

hower, 

from torchmoji.global_variables import PRETRAINED_PATH seems to find the file of 
pytorch_model.bin. in this pytorch_model.bin file, bert is used.

**Comment by chenyangh** [comment]
Hi,
Sorry I did not make this clear in the Readme file. The _pytorch_model.bin_ is the file for torchMoji pretrained model. It is a binary file downloaded by using this repo https://github.com/huggingface/torchMoji (by their code of scripts/download_weights.py).  I can not include it in my repo because it exceeds the size limit of GitHub.

**Comment by chenyangh** [comment]
I will update the Readme file correspondingly, soon.
