### ISSUE TITLE
code missing 

### ISSUE THREAD

**Issue by Jiayuforfreeo** [chenyangh/SemEval2019Task3#4]
for example, trainer_bert.py has "opt.half" in line53, while it doesn't define half in parer.parse_args()...

**Comment by chenyangh** [comment]
Sorry that I did not clean the code completely. You can just remove the related code. The half option was used to experiment with half precision computation so that I could have a larger batch size and faster speed. It requires the Apex package, but it wasn't numerical stable by then, so I gave up on the idea eventually. I will also update the python file in my repo soon. Thanks for being interested in my code.

**Comment by Jiayuforfreeo** [comment]
It's so kind of you to give a feedback on this issue, hope to see your
updated repo soon.

Chenyang Huang <notifications@github.com> 于2019年6月19日周三 上午10:46写道：
